### ISSUE TITLE
Logo / T-Shirt Desgin

### ISSUE THREAD

**Issue by mjg-foundation** [mjg-foundation/passport2-monero#14]
I'm in talks with https://fosswear.store/ about adding a design to the store for this project. All proceeds of sales would go to a multisig, viewable wallet that would pay out bounties. If the project is ever "done", leftovers will be paid out to other FOSS projects TBD. I don't intend to enrich myself through this project, and I'm only comfortable accepting funding this way because a product is being provided, and a transparent multisig will be used.

While making the logo, feel free to think of a new name for the project, as passport2-monero isn't very slick.

Design Requirements:
- Include a logo for the project, and a large graphic for the back, both as transparent SVG files
- Follow good opsec, don't spur on any wrench attacks
  - avoid explicit XMR logo usage
  - avoid complete depictions of passport
  - XMR colors encouraged
- Don't use foundation devices branding, this is an unofficial project and I don't want copyright trouble
- Keep the logo simple
- The back graphic can be more interesting
- Create a PR with your submission if you would like the github clout, otherwise upload submissions and I will make a PR for the winner.
- The winner for the logo and the winner for the back graphic may be different people.

Some ideas:
- Themes of cold wallets, ice, air, and retro phones
- Themes of forking, cloning, and FOSS

Bounties: .5 XMR for the logo, .5 XMR for the back graphic, paid out upon approval from me and fosswear.store.

**Comment by xrybxby** [comment]
![foundationxmrforkv1](https://user-images.githubusercontent.com/98752729/236238485-6d250e37-7390-4c80-9a0a-c491523e0083.png)

**Comment by mjg-foundation** [comment]
That looks great! Could you upload an SVG?

**Comment by xrybxby** [comment]
![foundationxmrforkv2](https://user-images.githubusercontent.com/98752729/236319509-2bf85a1a-ce46-4b5f-a0f9-80e34b60825e.svg)


> That looks great! Could you upload an SVG? Is there any way to fix some of the misaligned tiles in the background?

better?

**Comment by xrybxby** [comment]
> That looks great! Could you upload an SVG? Is there any way to fix some of the misaligned tiles in the background?

https://svgshare.com/i/soc.svg

better?

**Comment by mjg-foundation** [comment]
There's still quite a bit of misalignment in the background tiles, what tool are you using to generate those?

**Comment by xrybxby** [comment]
the pattern for the background i just nabbed from midjourney cuz im short for time but I can make it fresh in adobe tomorrow if you think the concept is really worth it. Whats the timeframe for this?

**Comment by iamestellaescala** [comment]
interested, is there any deadline for this?

**Comment by xrybxby** [comment]
> > the pattern for the background i just nabbed from midjourney cuz im short for time but I can make it fresh in adobe tomorrow if you think the concept is really worth it. Whats the timeframe for this?
> 
> There's no tight timeframe, this is more of a competition once we get a couple more submissions in. If you're the only submission in the next couple weeks, you'll win by default.
> 
> Btw I do think the concept is worth it @xrybxby This is for the logo right?

Oh sweet that gives me loads of time. And yeah for the logo , nothing really came to mind for the shirt design. Maybe when I've perfected the logo entry I'll come up with something

**Comment by mjg-foundation** [comment]
> interested, is there any deadline for this?

Not really, lets say a few weeks for now. I want to give people a chance to participate without having it drag on.

**Comment by xrybxby** [comment]
@mjg-foundation is there a better way to contact you or is replying to this thread the best method to ask questions about stuff related to this?

**Comment by mjg-foundation** [comment]
> @mjg-foundation is there a better way to contact you or is replying to this thread the best method to ask questions about stuff related to this?

I like to keep things public, whatever questions you have will probably help others. If you want to go back and forth on design with me, message me on twitter @ShrtCrct6102

**Comment by xrybxby** [comment]
@mjg-foundation 
logo https://svgshare.com/i/sr1.svg
(shirt?) design/name idea
![mpassback](https://user-images.githubusercontent.com/98752729/236553375-cd5514be-ff66-46ae-8c1e-f8fe2b07ace2.png)
When i tried uploading the design/name idea it scrapped the font for some reason so let me know what you think with the png embed :) Hopefully I'm getting closer to the mark. I picked M:PASS because it sounds like Impasse and M for Monero and PASS short for Passport. IDK. Thoughts haha ^_^

**Comment by mjg-foundation** [comment]
Great work on the logo, I like that it can be translated to the shirt as well. M:PASS is nice and concise, so it could definitely be a contendor for the name. It seems like logo still has some blurriness around the lock. Are you creating this natively as an SVG, or a PNG?

**Comment by xrybxby** [comment]
PNG i guess I've never worked with SVG's before I can do a little research on them

**Comment by xrybxby** [comment]
@mjg-foundation is the blurriness the shadow? I can remove that entirely if its not to your liking

**Comment by mjg-foundation** [comment]
The shadow's fine, I can just see more artifacts of scaling up from a PNG on the lock

**Comment by xrybxby** [comment]
I hope I'm trying to fix the right thing here, i recreated components of the lock that appeared "blurry" if i zoomed in loads on my monitor but i think I feel like im limited by my own eyes/monitor :(  
logo https://svgshare.com/i/ss8.svg
design
![mpassback](https://user-images.githubusercontent.com/98752729/236625246-fe18bc13-4eae-4423-8f61-a1542e71bbd4.png)

**Comment by mjg-foundation** [comment]
That's better, but the issue still remains that I need a native SVG, not a PNG converted to an SVG.

**Comment by xrybxby** [comment]
photoshop doesn't support svg natively, sorry :/

**Comment by xrybxby** [comment]
is this thread dead now?

**Comment by mjg-foundation** [comment]
> is this thread dead now?

seems like it
I know an anon who's working on it though

**Comment by xrybxby** [comment]
> > is this thread dead now?
> 
> seems like it I know an anon who's working on it though

aw was hoping i'd still win by default somehow after all those hours i put in, i couldn't do it native svg though so its worth nothing i guess. Best of luck on the project!

**Comment by detherminal** [comment]
Is this still available?

**Comment by mjg-foundation** [comment]
> Is this still available?

Yep!

**Comment by detherminal** [comment]
![M PASS](https://github.com/mjg-foundation/passport2-monero/assets/76167420/95d3e9b9-565e-48de-9e8b-c83eeb2ac0c3)

Background is Monero's gray and front color is Monero's orange

The text is the same font as Monero logo MoneroGothic Bold

**Comment by detherminal** [comment]
Hey @mjg-foundation Didnt you like the icon? I can change the lock and background if you want

**Comment by mjg-foundation** [comment]
fosswear.store is gone, so this issue is dead. Sorry for any wasted effort.
