### ISSUE TITLE
Monero Icon

### ISSUE THREAD

**Issue by mjg-foundation** [mjg-foundation/passport2-monero#2]
We need a transparent, 20x20 monero logo that has the same properties as this bitcoin logo:
![ICON_BITCOIN__CF_INDEXED_2_BIT](https://user-images.githubusercontent.com/114431859/233537975-118514df-d823-46ff-801f-935142a5d51e.png)
It should be in a 2 bit color font.
Bounty: .1 XMR

**Comment by 4rkal** [comment]
Done
Hope this one is ok:

![monero_logo_20x20_nobg](https://user-images.githubusercontent.com/89646772/233589068-efa87659-c308-4729-9e65-5562ff1ddfe0.png)

Address :

87GaAhqZP9V5bJxGu9HExq8qjmUU5Br6gUZiRL4o9Ciu9eztWv44pZfC2rtBgKqFvNEBnqGnLB7Kq7kFrQ1WiKQQCQo9eN2

**Comment by mjg-foundation** [comment]
![snapshot-$j-18:40:31](https://user-images.githubusercontent.com/114431859/233749387-27482f6a-10e0-4181-83b8-18c4c9166dec.png)
![snapshot-$j-18:40:30](https://user-images.githubusercontent.com/114431859/233749388-85fc285a-dbed-44ab-aa62-9091763ff8d9.png)
![snapshot-$j-18:40:28](https://user-images.githubusercontent.com/114431859/233749389-bc70273f-0b15-4d39-8bf7-88466478838e.png)
![snapshot-$j-18:39:45](https://user-images.githubusercontent.com/114431859/233749390-30f4905a-f1a1-4255-8fae-795c0c2ffb5f.png)
![snapshot-$j-18:39:43](https://user-images.githubusercontent.com/114431859/233749391-ca1ec4da-c822-4b73-b3e4-467105c076e3.png)
![snapshot-$j-18:39:40](https://user-images.githubusercontent.com/114431859/233749393-c258fdb7-ad20-4635-a55d-4ae31c163ea5.png)

Looks great guys! I'll pay out as soon as possible!

**Comment by mjg-foundation** [comment]
![20230421_184352](https://user-images.githubusercontent.com/114431859/233749644-808a7806-1e5d-4cfb-84e5-9dcae0f6c52f.jpg)

Here's the real thing

**Comment by mjg-foundation** [comment]
Sent bounties! Thanks @wrkerr @4rkal !

**Comment by mjg-foundation** [comment]
@wrkerr @4rkal please confirm you received the payouts then I'll close the issue

**Comment by wrkerr** [comment]
Got it. It looks great. Thank you so much!

**Comment by mjg-foundation** [comment]
Gonna close this, since I sent both payments in one tx, and your confirmation is good enough for me
